### ISSUE TITLE
Ask for UAC privilege only when needed

### ISSUE THREAD

**Issue by poscat0x04** [wormtql/yas#100]
Currently, `yas` always asks for UAC privilege, even when you're just trying to check what CLI arguments the program takes using `yas.exe --help`. This is a bit annoying for the user and honestly also a bit suspicious. It would be nice if the UAC elevation can be done as needed. `yas` could achieve this by dropping `requireAdministrator` in the manifest and explicitly asking for UAC privilege after the CLI arguments have been parsed.

**Comment by wormtql** [comment]
I believe for most users it's not necessary to check `--help`, it's convenient to start yas by just double-clicking.
Since it's opensource, I think it's safe to ask for privilege.
