### ISSUE TITLE
散兵名字识别错误

### ISSUE THREAD

**Issue by tautomer** [wormtql/yas#115]
角色名字识别应该是被限制在了已有角色名字的字符集里面的吧，但是散兵的名字可以自己改，所以就出现了很搞笑的结果

比如我的散兵被识别成了莫桃。。。

![image](https://user-images.githubusercontent.com/15900605/229666491-9a540707-9ed6-4121-9e1f-b627ee892e33.png)

```json
{
   "setName":"shimenawaReminiscence",
   "position":"flower",
   "mainTag":{
      "name":"lifeStatic",
      "value":4780.0
   },
   "normalTags":[
      {
         "name":"critical",
         "value":0.09699999999999999
      },
      {
         "name":"elementalMastery",
         "value":51.0
      },
      {
         "name":"recharge",
         "value":0.10400000000000001
      },
      {
         "name":"criticalDamage",
         "value":0.078
      }
   ],
   "omit":false,
   "level":20,
   "star":5,
   "equip":"莫桃"
}
```

所以估计主角也有类似的问题？不过我的黄毛阿姨没有圣遗物，所以不知道具体情况怎么样

**Comment by poly000** [comment]
据 @wormtql 所说OCR模型是针对训练的……
如果拿出来提瓦特中文字体做通用的针对训练应该可以

**Comment by tautomer** [comment]
> 据 @wormtql 所说OCR模型是针对训练的……

看到莫桃这俩字就猜到应该是这么来的了

不过考虑到现在所有角色里面只有散兵和旅行者会有这个问题，更简单的解决方案恐怕直接给个warning让用户自己改json拉倒。尤其是考虑这俩名字甚至可以有特殊字符，想从模型解决恐怕就不单是中文的问题了。。。

明天试试我的旅行者（DeepDarkFanta）会被识别成什么。。。

**Comment by wormtql** [comment]
移步#176
