### ISSUE TITLE
不使用原神启动器直接启动原神无法识别扫描圣遗物

### ISSUE THREAD

**Issue by DLGum** [wormtql/yas#127]
如题。
我是从安装目录把游戏本体创建了快捷方式。

**Comment by poly000** [comment]
目前判断窗口是靠标题，应该加上 GenshinImpact.exe 和 Yuanshen.exe 就好

**Comment by lyjohn0921** [comment]
建议修改https://github.com/wormtql/yas/blob/b54f765097c157e73930b3f5761458771e70539b/src/common/utils/windows.rs#L50
