### ISSUE TITLE
多屏用户无法正确识别的解决方法

### ISSUE THREAD

**Issue by zhangyina1** [wormtql/yas#131]
个人设置：左右双屏，主用左屏，右屏设为主屏，此时的分辨率是左侧副屏从-1920开始，右侧主屏从0开始

解决方法：

1. 在  win+i->系统->屏幕->多显示器  中修改“扩展这些显示器”为其他三个选项，双屏会记录桌面图标位置，更多屏不知道
2. 在1同位置将最左侧屏幕设为主屏，再使用win+shift+←把游戏移动到主屏（快捷键对常见全屏游戏也有效）
3. 拔到只剩一个显示器的hdmi、dp之类的数据线，主板侧或者显示器侧都可以

问题描述：
当游戏窗口在左侧的副屏运行时，会出现<a href="https://github.com/wormtql/yas/issues/117">#117</a>的问题，即：
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "capture failed"', src\common\mod.rs:69:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
当游戏窗口在右侧的主屏运行时，可以解决#117的问题，但在读取圣遗物数量的时候出现了识别错误
猜测是找目标位置的时候加上了-1920或者是使用的函数从屏幕最左侧开始找，结果是找到左侧屏幕对应的圣遗物数量位置

<details>
<summary>另外稍微解释一下为什么这么设置多屏</summary>

> 很多软件偷懒（所以作者偷懒也不是不能理解，并且小小支持一下），对副屏支持不好，个人体验windows系统本身的支持就不算好，此外某聊天软件，开机启动后会固定出现在主屏，某些安全、下载软件的悬浮窗，只能出现在主屏，这些使用频率不高不低的东西会一直占用主屏而不好扔到副屏
> 个人的解决方式是把副用的屏幕设为主屏，非常好用

</details>

**Comment by yzxjoe** [comment]
我是3个屏，也遇到同样的问题（之前还能用的），受你的启发，拔掉只剩下一个屏就好了

**Comment by zhangyina1** [comment]
> 我是3个屏，也遇到同样的问题（之前还能用的），受你的启发，拔掉只剩下一个屏就好了

那你要不要试试我提的pr在3屏上用着咋样(

**Comment by yzxjoe** [comment]
那个也看了，看不懂，哈哈哈哈

**Comment by Sarasuberi** [comment]
大约是没有对多屏进行检测的问题，我是放到了主屏上就可以了

**Comment by Sarasuberi** [comment]
但奇怪的是，我旧版本（没有版本号，是因为扫描4.0圣遗物报错后升级的）三屏可以正常使用(

**Comment by wormtql** [comment]
多屏幕问题移步#175
