### ISSUE TITLE
1280*960分辨率下部分圣遗物副词条有误

### ISSUE THREAD

**Issue by zjc2023** [wormtql/yas#135]
![image](https://github.com/wormtql/yas/assets/136285605/09aba915-67ca-483d-9a81-60e714d59ed6)
![image](https://github.com/wormtql/yas/assets/136285605/73f6c7bc-5b2c-4ef4-9087-2cadeeb3f6d6)
![image](https://github.com/wormtql/yas/assets/136285605/1b19d212-2a73-4791-918f-8cb03485271c)
![image](https://github.com/wormtql/yas/assets/136285605/09788037-e3d5-4522-8434-c035685e18a0)
![image](https://github.com/wormtql/yas/assets/136285605/6ec8cca2-62b3-4f84-8290-aaee8ba5d1bf)
![image](https://github.com/wormtql/yas/assets/136285605/347a822a-d944-4d32-b34e-e311a0ec1e11)
![image](https://github.com/wormtql/yas/assets/136285605/60a78eae-cc7b-4f39-a413-f768d9469691)
![image](https://github.com/wormtql/yas/assets/136285605/e7ba3a92-f690-4b01-bb0a-91b0647ae211)
![image](https://github.com/wormtql/yas/assets/136285605/6a91699a-584e-45fd-8c50-93e0353ea958)
分辨率切换到1600x900后问题消失

**Comment by wormtql** [comment]
分辨率低不利于识别
