### ISSUE TITLE
星穹铁道的导出目前有适配哪些计算器

### ISSUE THREAD

**Issue by LaoshuBaby** [wormtql/yas#148]
~~（还是说没有计算器？）~~

（因为看起来隔壁莫娜有人问 https://github.com/wormtql/genshin_artifact/issues/281 和 https://github.com/wormtql/genshin_artifact/issues/291）
（希望更新以下README？）

**Comment by YCR160** [comment]
有做一个类似莫娜计算器的打算（新建文件夹

**Comment by FiiiiVe** [comment]
我还在找星铁如何导出 :(

**Comment by MrSnake0208** [comment]
> 有做一个类似莫娜计算器的打算（新建文件夹
简单用pyside6做了个带GUI的，详细算法借鉴了一下 星穹铁道工坊 小程序，勉强能跑，但是代码非常狗屎，如若需要可分享
![image](https://github.com/wormtql/yas/assets/74225450/eabdaf9c-29f8-49fd-b34a-a8e64db5add1)

**Comment by LaoshuBaby** [comment]
> 但是代码非常狗屎，如若需要可分享

这主要看大佬您有没有开源的意愿了，就我来说有能用的工具算一下肯定是比口算+演草本+截图窗口开一堆记录要好得多的

（不过您是怎么导出的圣遗物的数据的？）

**Comment by MrSnake0208** [comment]
> > 但是代码非常狗屎，如若需要可分享
> 
> 这主要看大佬您有没有开源的意愿了，就我来说有能用的工具算一下肯定是比口算+演草本+截图窗口开一堆记录要好得多的
> 
> （不过您是怎么导出的圣遗物的数据的？）

开源有点不太好意思，等我这几天再改改，大概一周左右，代码非常丑陋，不过外在能看。
导出遗器数据的话我用的是
https://github.com/YCR160/yas/tree/modification
就是上面那位的仓库，它对yas做了对星铁的适配。
![0b633ba4109cd172d8a88e62f6f6f98](https://github.com/wormtql/yas/assets/74225450/249722d4-1ed5-4d58-abdc-6764b5a52f07)

**Comment by YCR160** [comment]
[yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14278961/yas_scanner_starrail.zip)
这里有一份编译好的星铁扫描器，可以扫描 2.0 之前的遗器，这个版本的遗器模型还在训练。

**Comment by MrSnake0208** [comment]
> [yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14278961/yas_scanner_starrail.zip) 这里有一份编译好的星铁扫描器，可以扫描 2.0 之前的遗器，这个版本的遗器模型还在训练。

十分感谢！

**Comment by LaoshuBaby** [comment]
> 后续我看看能不能推进崩铁遗器计算器的时候把问题都解决了

您会不会考虑……干脆把计算器分离成一个纯后端的，fastapi或者django都无所谓，然后前端可以直接用现在的qt也或者未来有可能希望有人会做个前端（？）

（不过倒也不会有mona那么多功能？因此也不一定需要前端很好看？）

~~（不好，这层的层主已经开始说胡话了x）~~

**Comment by MrSnake0208** [comment]
> > 后续我看看能不能推进崩铁遗器计算器的时候把问题都解决了
> 
> 您会不会考虑……干脆把计算器分离成一个纯后端的，fastapi或者django都无所谓，然后前端可以直接用现在的qt也或者未来有可能希望有人会做个前端（？）
> 
> （不过倒也不会有mona那么多功能？因此也不一定需要前端很好看？）
> 
> ~（不好，这层的层主已经开始说胡话了x）~

我是今天才开始开发的，想着先本地用上，前端的话（主要是我不太会哈哈哈哈），后续会改成fastapi或django的

**Comment by ainopara** [comment]
![ScreenShot-2024-02-14-5274](https://github.com/wormtql/yas/assets/1849450/746320ea-a88f-4302-a164-69fa17f7b8db)
我开发了一个 macOS 应用，用来对圣遗物进行扫描、评分、加锁，需要配合我 fork 的 yas 版本使用。
目前自用效果还可以，不过因为 macOS 应用需要一台玩家有一台 mac 才能运行，受众太小，就一直没推动对外发布的事情。
我准备后续改成 web 应用后开源 web 版社区共同维护。

**Comment by MrSnake0208** [comment]
> ![ScreenShot-2024-02-14-5274](https://private-user-images.githubusercontent.com/1849450/304736767-746320ea-a88f-4302-a164-69fa17f7b8db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTU5MDYsIm5iZiI6MTcwNzkxNTYwNiwicGF0aCI6Ii8xODQ5NDUwLzMwNDczNjc2Ny03NDYzMjBlYS1hODhmLTQzMDItYTE2NC02OWZhMTdmN2I4ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTMwMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkwMTBhZmExMDQwY2Q2NDMzMzdhMWI4YTMwN2VmMzg1ZWZlMmIwZGU1NDRhOTg3YjI1NGQ3MmE1Y2YyZTcyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hEtlfn2JrbtqLPFqCu5MeNe3H6W-FG5p5GSIIYTd6hQ) 我开发了一个 macOS 应用，用来对圣遗物进行扫描、评分、加锁，需要配合我 fork 的 yas 版本使用。 目前自用效果还可以，不过因为 macOS 应用需要玩家有一台 mac 才能运行，受众群体太小，就一直没推动对外发布的事情。 我准备后续改成 web 应用后开源 web 版社区共同维护。

可以一搞！

**Comment by LaoshuBaby** [comment]
没想到目前已经有这么多版本的yas fork了吗！

> 可以一搞！

可以一搞！(楼上的几位在yas的README记载的QQ群里吗？准备私聊几位了）

https://github.com/wormtql/yas/blob/0ae7bb76494f153a9004dff2bdeff807a31c3ba5/README.md?plain=1#L35-L37

**Comment by MrSnake0208** [comment]
申请了还没通过😁

快乐的老鼠宝宝 ***@***.***> 于2024年2月14日周三 21:14写道：

**Comment by MrSnake0208** [comment]
> 没想到目前已经有这么多版本的yas fork了吗！
> 
> > 可以一搞！
> 
> 可以一搞！(楼上的几位在yas的README记载的QQ群里吗？准备私聊几位了）
> 
> https://github.com/wormtql/yas/blob/0ae7bb76494f153a9004dff2bdeff807a31c3ba5/README.md?plain=1#L35-L37

申请了但是还没通过

**Comment by YCR160** [comment]
> [yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14278961/yas_scanner_starrail.zip) 这里有一份编译好的星铁扫描器，可以扫描 2.0 之前的遗器，这个版本的遗器模型还在训练。

[yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14283661/yas_scanner_starrail.zip)
2.0 的模型训好了。

**Comment by MrSnake0208** [comment]
也许我们可以先加一下dc？
https://discord.gg/mQc9GVwG

**Comment by AshHuangQ** [comment]
> > [yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14278961/yas_scanner_starrail.zip) 这里有一份编译好的星铁扫描器，可以扫描 2.0 之前的遗器，这个版本的遗器模型还在训练。
> 
> [yas_scanner_starrail.zip](https://github.com/wormtql/yas/files/14283661/yas_scanner_starrail.zip) 2.0 的模型训好了。

您好，有人在NGA上发布了一个微信小程序的遗器配装助手，但是他苦于识别遗器这个问题，目前是通过角色展柜导入。小程序叫 黑塔配装助手

**Comment by YCR160** [comment]
- yas 获得遗器数据需要与电脑版的游戏交互。
- 在手机上没有很好的扫描仓库遗器的方法。
- 通过角色展柜获取的遗器数据精度更高，不过一次只能获取一小部分，并且更新有延迟。

**Comment by AshHuangQ** [comment]
> * yas 获得遗器数据需要与电脑版的游戏交互。
> * 在手机上没有很好的扫描仓库遗器的方法。
> * 通过角色展柜获取的遗器数据精度更高，不过一次只能获取一小部分，并且更新有延迟。

他本身也是电脑用户，只是他的程序是基于小程序，他本人表示“识别导入我目前是完全没有相关知识储备，要自己做很花时间，最好是有人做出了导出工具之后我去做导入数据的支持就完事了。”，大佬你现在有做支持2.1版本的崩铁yas吗

**Comment by YCR160** [comment]
有的，在这里可以下载最新版本的崩铁 yas https://github.com/wormtql/yas/issues/164#issuecomment-1952284022

**Comment by AshHuangQ** [comment]
> 有的，在这里可以下载最新版本的崩铁 yas [#164 (comment)](https://github.com/wormtql/yas/issues/164#issuecomment-1952284022)

好的感谢大佬，我也去给他提一下

**Comment by Furina113** [comment]
已经有外服的大佬做出来了
扫描器：https://github.com/kel-z/HSR-Scanner
计算器：https://fribbels.github.io/hsr-optimizer
教程：https://www.bilibili.com/video/av1503560292/?p=1&t=0

**Comment by LaoshuBaby** [comment]
https://github.com/fribbels/hsr-optimizer/pull/336

暮雨终将落下，此贴完结
