### ISSUE TITLE
在非中文系统上显示为乱码

### ISSUE THREAD

**Issue by onefork** [wormtql/yas#15]
![image](https://user-images.githubusercontent.com/1749333/140661199-171cf8ae-ff1f-4f96-96a7-ce657755d0ce.png)

工具本身很好用，多谢！

**Comment by jimmyyou** [comment]
装个支持utf-8的shell应该就好了，比如新的windows power shell

**Comment by onefork** [comment]
> 装个支持utf-8的shell应该就好了，比如新的windows power shell

测试了0.1.5，似乎当前版本的codepage是GBK/CP936

**Comment by MakiseKurisu** [comment]
> 装个支持utf-8的shell应该就好了，比如新的windows power shell

yas需要管理员权限，而在Windows上直接右键管理员运行[只能使用conhost](https://github.com/microsoft/terminal/issues/10276#issuecomment-852215012)作为shell
需要添加i18n

**Comment by wormtql** [comment]
问题过老，还有问题请新开issue
