### ISSUE TITLE
当最后一页圣遗物无法铺满一页时，貌似会出现翻页错误

### ISSUE THREAD

**Issue by lijian12345** [wormtql/yas#150]
比如像这样筛选之后，总共53个圣遗物；当第一页40个扫描完，第二页只有13个，程序会表现为连续向下滚多次滚轮，然后报翻页错误的情况
![image](https://github.com/wormtql/yas/assets/26590220/639c09f2-ec03-4fc9-b619-8de9ebbd79dd)

**Comment by wormtql** [comment]
yas带有处理这种情况的逻辑，如果失败，可能是圣遗物总量识别错误

**Comment by lijian12345** [comment]
> yas带有处理这种情况的逻辑，如果失败，可能是圣遗物总量识别错误

我猜总量是在扫描完成后才统计得出的吧，像这种中途无法滚动下去的情况，是不是还没到得出总量那一步？

**Comment by Omico** [comment]
问题出在这里，今天遇到相同的情况。

![image](https://github.com/wormtql/yas/assets/14316223/a2f52e17-2494-46e7-b730-4e5c9d73cde5)
![image](https://github.com/wormtql/yas/assets/14316223/424bd80b-a999-46d9-a8fe-52b68da4cf1d)
