### ISSUE TITLE
0.1.14版本的圣遗物导出工具貌似对带鱼屏导出始终都是会失败的？

### ISSUE THREAD

**Issue by nemofusion** [wormtql/yas#151]
0.1.14版本的圣遗物导出工具貌似对带鱼屏导出始终都是会失败的？
调整分辨率到1920*1080还是不行....

**Comment by foxleeda** [comment]
带鱼屏需要先调整到1920*1080，然后重启游戏，不重启不行。重启后，会发现圣遗物每排有变化，然后再扫描
