### ISSUE TITLE
wine + wayland + hidpi 艰难地跑起来了！

### ISSUE THREAD

**Issue by lilydjwg** [wormtql/yas#152]
花了我俩小时，修修补补，终于跑起来了！过程中遇到的问题如下：

* proc_macros2 报错。这个简单，`cargo update` 到最新版解决。
* 不知道为什么解析不了 xwininfo 的输出。硬编码屏幕尺寸绕过。
* 用 portal 截图太麻烦了。改用 wlroots 自有协议截图。使用 screenshots-rs git 版，直接删掉前两个支持。然后发现 yas 与该版本并不兼容。手动改了一下（不用自己解析 PNG 了，但要把 rgba 转成 rgb 格式；使用 `screenshots::image` 而非 `image` 以保证版本一致性）。
* 又发现 screenshots-rs 给 wayshot 传的物理像素坐标，但是 wayshot 只支持缩放后的大小。改了一下，虽然这样一来截图变糊了，但 yas OCR 能力挺强的，依旧能正确识别。
* 然后 yas 终于能跑了，但是它点不中圣遗物。想了想，应该是 wine 用的物理像素坐标，但是截图用的缩放后的坐标。把移动鼠标那里的坐标 x2，解决。

**Comment by wormtql** [comment]
膜大佬
