### ISSUE TITLE
0.1.14扫描启动时闪退

### ISSUE THREAD

**Issue by NocturneMao** [wormtql/yas#154]
分别把分辨率调节为1600x900, 1920x1080, 3840x2160，退出重进游戏，背包第一行，右键管理员yas，都闪退。手机视频勉强拍到以下报错画面：
![dec95062542df5807a317341c711d37](https://github.com/wormtql/yas/assets/67298933/5f5c6901-ea8a-41cd-b140-8cabd305d52a)

**Comment by KINOVE** [comment]
群内反馈补充，web UI，分辨率为2K，游戏分辨率1600*900：

![image](https://github.com/wormtql/yas/assets/41948123/dfdcef98-264d-49b8-8af2-eaa9d8407e9a)

**Comment by KINOVE** [comment]
群内反馈补充，游戏重启仍报错：

![c796c52d975afe57f71627d1042dd7df](https://github.com/wormtql/yas/assets/41948123/0d7d1828-2ef2-4cb3-895a-14eaeaa85a3c)

**Comment by KINOVE** [comment]
> 群内反馈补充，游戏重启仍报错：
> 
> ![c796c52d975afe57f71627d1042dd7df](https://private-user-images.githubusercontent.com/41948123/292670666-0d7d1828-2ef2-4cb3-895a-14eaeaa85a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjIyOTksIm5iZiI6MTcwMzQyMTk5OSwicGF0aCI6Ii80MTk0ODEyMy8yOTI2NzA2NjYtMGQ3ZDE4MjgtMmVmMi00Y2IzLTg5NWEtMTRlYWVhYTg1YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEyNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWYwMDcwODIyYjM1YWE4NzE3ZjQ5NjljM2NjODA2NjU3NDAzZTViMDk0ZTQyYTllMjk5NjI1YmJiOTkyYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UZguxs1eIjVbGTptIaXhKDjIUDb-ueKkUb7W7s3kAz8)

经过确认，是多屏用户。最终以屏幕显示方案暂时切换为单屏解决：

![image](https://github.com/wormtql/yas/assets/41948123/8cecc182-6e0d-489f-932a-fcf3a18c8e19)

出现此问题的用户可以尝试暂时切换为单屏尝试解决。

**Comment by wormtql** [comment]
多屏幕问题移步#175
