### ISSUE TITLE
双显示器环境下，翻页出现问题，

### ISSUE THREAD

**Issue by xbhoneybee** [wormtql/yas#160]
version:0.1.15
翻页出现问题，
error count: 40

外接2k显示器（设为主显示器），1080P窗口模式下识别很慢，且无法正常翻页。
建议在Readme 提示：推荐只使用一个显示器
最后找到 https://github.com/wormtql/yas/issues/134 只用一个显示器，改1080P 窗口模式可以翻页，速度很快。

**Comment by MntCer** [comment]
同样遇到这个问题，您的方案很有效！确实又快又好哈哈哈哈哈，感谢！

**Comment by wormtql** [comment]
多屏幕问题移步#175
