### ISSUE TITLE
为什么扫到三星圣遗物就停止了？

### ISSUE THREAD

**Issue by Zlyh66** [wormtql/yas#161]
我班尼特的圣遗物还不是很好，但是这个工具它扫到我的三星圣遗物的时候，他就停止扫描了。
因为我班尼特带的教官，且是最近一个月才开始收集，所以没那么好集齐四星级的，希望能修复一下下。
如果不修复的话，除非我把那个三星圣遗物分解掉，不然的话它就永远占在五星圣遗物中间，且工具运行时扫到它就会停止。

**Comment by wormtql** [comment]
默认不扫三星，因为意义不是很大，要扫三星需要配置，看Readme
