### ISSUE TITLE
部分角色名字无法识别

### ISSUE THREAD

**Issue by wutuo6** [wormtql/yas#173]
莱依拉名字识别不出来
打开显示详细信息的结果
![2](https://github.com/wormtql/yas/assets/79790756/20b2ab83-de07-448f-96a1-27fa6684ba09)
扫描内容
![1](https://github.com/wormtql/yas/assets/79790756/515efff1-18e4-404c-8807-ac096e84cd41)

翻了一下源码发现`src/common/character_name.rs`中也漏了一些角色的名字，这些角色同样也识别不了，有绮良良、莱欧斯利、夏洛蒂（这些是4.3版本之前的

**Comment by YCR160** [comment]
https://github.com/wormtql/yas/blob/main/src/common/character_name.rs#L57

**Comment by wormtql** [comment]
已添加新的角色名
