### ISSUE TITLE
0.1.15双屏21:9无法识别

### ISSUE THREAD

**Issue by learningAHAIC** [wormtql/yas#174]
![temp](https://github.com/wormtql/yas/assets/126245543/06507b12-61ea-402b-ae83-c59a8858c4e0)
如图，扫描到第二个开始报错，半秒后程序直接退出。不会rust，只看到一个out of bound，不清楚是什么问题

**Comment by YCR160** [comment]
https://github.com/wormtql/yas?tab=readme-ov-file#%E6%B3%A8%E6%84%8F
https://github.com/wormtql/yas/issues/134
暂时不支持多屏，也暂时不支持 21:9。
可以尝试拔掉其余的显示器，把游戏长宽比调整为 16:9。

**Comment by lingo76** [comment]
我也有这个问题，原神分辨率设置到1920*1080 
重启原神 就能扫描了。
我也是双屏 带鱼屏

**Comment by wormtql** [comment]
移步#175
