### ISSUE TITLE
新版本运行提示扫描发生错误：翻页超时

### ISSUE THREAD

**Issue by Anno111** [wormtql/yas#192]
![b8866ce6-3d15-4530-879e-e6e28c19cfc5](https://github.com/user-attachments/assets/1184d1d8-394b-4e33-a708-6c19b9824651)
感觉像是新版本更新后。圣遗物界面顶部新增了功能导致
![Uploading e4fda2a2-7b14-425a-bba6-6d1c5865f840.png…]()

**Comment by evanliu3594** [comment]
感觉是因为圣遗物页面最上面多了一行“按获得时间展示圣遗物”，导致原有的圣遗物点击区域失效了

**Comment by wormtql** [comment]
已支持

**Comment by telZhongshiji** [comment]
如何更新？没找到exe文件

**Comment by evanliu3594** [comment]
> 如何更新？没找到exe文件

主页右边release

**Comment by telZhongshiji** [comment]
> > 如何更新？没找到exe文件
> 
> 主页右边release

感谢
