### ISSUE TITLE
圣遗物识别数量错误

### ISSUE THREAD

**Issue by tseflcz** [wormtql/yas#26]
如题，1295个圣遗物只能识别出931个，目测可能是翻页的问题

**Comment by longwusha** [comment]
建议附上对应截图，不然排查和复现问题比较困难

**Comment by tseflcz** [comment]
> 建议附上对应截图，不然排查和复现问题比较困难
之前因为觉得截图大概也没什么帮助就没有截，之后为了截图又试了大概10次左右，有时候能正常识别，有时候不能，这样就似乎不是翻页的问题了。bug的触发条件暂不清楚，以下为触发bug时的截图以及用amenoma识别同一批圣遗物的截图。
![YuanShen_HpehO9Bwhg](https://user-images.githubusercontent.com/66352689/149619749-ce5c748b-feaf-4c56-ba4d-c70550b2264f.png)
![YuanShen_x9fMtnRRi2](https://user-images.githubusercontent.com/66352689/149619755-22bebf83-584e-4608-99fd-d2cfc4c0ada4.png)

**Comment by wormtql** [comment]
按图里来看并没有触发bug，默认只扫描4星和5星，所以会比总圣遗物数量少

**Comment by tseflcz** [comment]
所以我附上了amenoma的结果，正确数量是1298个5星，42个4星，35个3星，共1375个，怎么都对不上这里的995个

**Comment by wormtql** [comment]
目测是翻页的问题，但是可能不太容易修
