### ISSUE TITLE
请求支持win7 电脑

### ISSUE THREAD

**Issue by GokouMashiro** [wormtql/yas#36]
![1](https://user-images.githubusercontent.com/20145656/154800246-de774506-9b6b-46b7-b47d-b746b9bd2bce.PNG)

**Comment by Amenomori** [comment]
这是由于 yas 会调用系统中有关 HiPDI 的 API 以辅助识别，此 API 在 Win 8.1 及以上版本提供。
我们或许会在之后做一些对 Win7 的支持，但现在并不是主要计划。

This is error is known as an OS-related problem and may not be fixed in the recent roadmap.

**Comment by GokouMashiro** [comment]
好的 谢谢大佬
