### ISSUE TITLE
请求支持手机截图 / 共享屏幕的识别, 或者添加识别最上层应用 / 识别范围的选项

### ISSUE THREAD

**Issue by Hocnonsense** [wormtql/yas#38]
![image](https://user-images.githubusercontent.com/48747984/155874111-5a6899a0-e0a3-43b7-901e-2224dc430d2f.png)

感谢!

**Comment by lilydjwg** [comment]
+1

我是 Linux + Android 用户，因此在考虑通过 scrcpy 共享手机屏幕来采集和识别数据，但是手机版的布局是不同的（那一堆 winapi 的操作我可以替换为 Linux 命令行操作）。

**Comment by wormtql** [comment]
已经添加了移动端UI/云游戏支持，至少代码中是有的，可能需要更详尽的测试
