### ISSUE TITLE
有关对 macOS 的支持

### ISSUE THREAD

**Issue by spencerwooo** [wormtql/yas#41]
目前在使用 M1 芯片的 macOS 设备上可以借助 PlayCover 安装 iOS 版本的原神（详见 - [这篇文章](https://sspai.com/post/70602)），并使用「鼠标模拟触摸」的形式进行比如：点击选择圣遗物、下拉滚动圣遗物列表……的操作。请问本项目是否能够迁移到 macOS 上呢？（比如有使用 Windows-only 的 API 吗？）

目前我猜测可能出现的一些问题：比如窗口大小的识别、触摸下拉滚动页面……

由于我对 Rust 并不熟练，因此想先问问有没有可能做迁移，如果可能我很乐意上手帮忙 :)

**Comment by Amenomori** [comment]
yas 会调用 Windows 系统中有关 HiPDI 以及其他功能的 API 辅助识别。支持 PlayCover 会影响功能和代码的通用性，现在并没有迁移 macOS 的计划。

Recently there is no plan for other OS support.

**Comment by spencerwooo** [comment]
了解，感谢回答。
