### ISSUE TITLE
希望路径支持全路径中文格式

### ISSUE THREAD

**Issue by XTsat** [wormtql/yas#45]
现在最后一个路径如果是**中文**就会显示**不支持的分辨率**，而如果多套一层英文文件夹使最后一个文件夹是**英文**，而前面有**中文**可以正常使用

![Snipaste_2022-04-01_23-52-05](https://user-images.githubusercontent.com/44708609/161298760-8c9d5c3b-07c1-4207-8638-cd94555ef5e7.png)

![Snipaste_2022-04-01_23-52-22](https://user-images.githubusercontent.com/44708609/161298809-a6a8226f-02a6-498a-9b74-eefcf2f7c410.png)

**Comment by wormtql** [comment]
原因在于你的文件夹名叫“原神”，把这个文件夹改名，或者关掉，就可以了

**Comment by wormtql** [comment]
因为原神游戏的窗口就叫原神，yas的原理是检测mingjiao 原神的窗口，但不判断是不是真的原神窗口
