### ISSUE TITLE
新版本圣遗物副词条缺失的错误

### ISSUE THREAD

**Issue by tseflcz** [wormtql/yas#48]
v1.0.8版本的yas扫描部分圣遗物会识别不出第四条副词条，如下图为v1.0.8和v1.0.7扫描结果中一个圣遗物的对比，可以看到这个4级的圣遗物只有三个副词条。扫描过程全程无报错，这个错误是在将扫描结果导入其他工具分析时发现的。
![image](https://user-images.githubusercontent.com/66352689/161668875-92c4f570-03c0-4508-85bc-42bf2e60f873.png)

**Comment by wormtql** [comment]
试一下`yas --capture-only`看看输出啥

**Comment by tseflcz** [comment]
我找到该圣遗物输出的扫描结果有明显错位

**Comment by tseflcz** [comment]
保存下来的截图是有第四个词条的，应该是后续识别的问题。

**Comment by wormtql** [comment]
可以发一下截图吗

**Comment by tseflcz** [comment]
我后续发现识别错误的圣遗物全部是第四个词条为暴击伤害，仅在这种情况下会出现这个bug，我选取了一个较为清楚的圣遗物截图文件，可以看到截图上没有出现问题。另附0.1.7与0.1.8版本的扫描结果，可以通过类似vscode的代码比较的功能比较直观的看出问题全部出在第四个词条为暴击伤害的圣遗物上。
[captures.zip](https://github.com/wormtql/yas/files/8461444/captures.zip)

**Comment by wormtql** [comment]
新版模型可能会提高准确率
