### ISSUE TITLE
yas生成的mona.json导入莫娜提示格式错误

### ISSUE THREAD

**Issue by Li-Jiepeng** [wormtql/yas#50]
![微信图片_20220530132231](https://user-images.githubusercontent.com/71962681/170922307-eaafa8a2-1a63-4ffd-8692-f2d23972d190.png)

**Comment by wormtql** [comment]
要在圣遗物界面导入，而不是计算预设界面

**Comment by Li-Jiepeng** [comment]
您好，这是李洁鹏的邮箱，邮件已收到。我最近正在工作中，无法立即回复您的邮件。我将在工作结束后，尽快给您回复。
