### ISSUE TITLE
圣遗物是否加锁识别错误

### ISSUE THREAD

**Issue by Kumacytus** [wormtql/yas#51]
RT
在1600x900及1920x1080分辨率下均出现识别错误
表现为部分未加锁的识别为加锁，部分加锁的识别为不加锁
（导致后续使用yas-lock进行加解锁完全错乱…

另外，在全部未加锁下进行识别的话
会有一半圣遗物被识别为加锁

**Comment by wormtql** [comment]
yas本身并不会识别圣遗物锁没锁，你可能用的是yas-lock

**Comment by Kumacytus** [comment]
对不起我以为yas-lock也是这里做的
我去那边反应_(:з」∠)_
