### ISSUE TITLE
无法扫描

### ISSUE THREAD

**Issue by loolesszzzz** [wormtql/yas#52]
![image](https://user-images.githubusercontent.com/106914710/172050933-ea9ad7af-e7de-45a7-9782-37988abdbea0.png)
窗口化1600*900 artifacts界面 管理员运行 但是error 大佬能否看看哪出了问题

**Comment by wormtql** [comment]
这个实在看不出来是啥，需要你自行解决一下编码问题，然后看一下报错的内容到底是啥

**Comment by Patrick-Ze** [comment]
@loolesszzzz 编码问题是其一，另外你没有以管理员身份运行所以报这个错
