### ISSUE TITLE
希望可以添加一下各个角色专属方案计算的比较基准数据说明

### ISSUE THREAD

**Issue by AragakiSena** [wormtql/yas#53]
就是计算后那个计算了多少组搭配下方的具体方案排序选择那里，第一套应该都是100/XXXXX，后面这个XXXXX具体是指哪个数值能否添加一个说明。我配神子的时候也是碰巧发现XXXXX是三阶杀生樱的期望伤害，但是雷军的这个XXXX具体是哪个值就找不到了。应该是整个Q期间的全部伤害期望之和？希望能够添加这个说明

**Comment by wormtql** [comment]
这个就是目标函数的输出值，跟伤害相关，但是不一定是伤害值。会慢慢在目标函数说明里加入这个目标函数的计算目标
