### ISSUE TITLE
在UI有边界偏移的情况下，定位失效无法识别。

### ISSUE THREAD

**Issue by lshy1993** [wormtql/yas#54]
1600*900的窗口模式，扫描失败（无报错，没有扫到）。
![image](https://user-images.githubusercontent.com/6592646/174260238-12296043-ff5b-4b5d-a8a9-68a2fdb16cdd.png)
分析原因可能因为存在UI边界偏移：背包界面，圣遗物排列位置存在一定的偏移量。
![image](https://user-images.githubusercontent.com/6592646/174259988-3d45e44e-7480-42c8-962a-d41101a9547b.png)
![image](https://user-images.githubusercontent.com/6592646/174260051-bbcf5ba0-c77c-4769-8d1b-fedee02403fc.png)

**Comment by wormtql** [comment]
重启一下游戏可能可以解决
