### ISSUE TITLE
建议增加一个解锁所有圣遗物的功能

### ISSUE THREAD

**Issue by TaoRone** [wormtql/yas#55]
我以为有……结果并不是……
急需！！！
谢谢大佬！

![image](https://user-images.githubusercontent.com/22138142/177025164-f7409899-869e-4098-95fe-4b4f5fe5faaa.png)

**Comment by emako** [comment]
建议增加一个摧毁所有圣遗物的功能www

**Comment by lingyu0628** [comment]
可以扫描完毕后，导入到https://ideless.github.io/artifact/这个网站，然后全部解锁，导出到Yas同目录，打开Yas，会有提醒，就可以全部解锁了

**Comment by TaoRone** [comment]
> 可以扫描完毕后，导入到[https://ideless.github.io/artifact，这个网站，然后全部解锁，导出到Yas同目录，打开Yas，会有提醒，就可以全部解锁了](https://ideless.github.io/artifact%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%EF%BC%8C%E7%84%B6%E5%90%8E%E5%85%A8%E9%83%A8%E8%A7%A3%E9%94%81%EF%BC%8C%E5%AF%BC%E5%87%BA%E5%88%B0Yas%E5%90%8C%E7%9B%AE%E5%BD%95%EF%BC%8C%E6%89%93%E5%BC%80Yas%EF%BC%8C%E4%BC%9A%E6%9C%89%E6%8F%90%E9%86%92%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E5%85%A8%E9%83%A8%E8%A7%A3%E9%94%81%E4%BA%86)

稳！虽然已经退坑了，但还是谢谢大佬指明方向！
