### ISSUE TITLE
物伤杯识别错误

### ISSUE THREAD

**Issue by yeyup** [wormtql/yas#56]
多次实验，物伤杯一直报错。
总共3个物伤杯，都装备了的情况
![image](https://user-images.githubusercontent.com/101948567/179421251-54e40f07-6c4f-4bb3-bf2a-4e4e1a7a815f.png)
都没装备的情况
![image](https://user-images.githubusercontent.com/101948567/179421378-c02a9659-8ac2-4d85-a150-b6801eae9676.png)

**Comment by wormtql** [comment]
试试新版
