### ISSUE TITLE
命令行指定圣遗物最小等级无效

### ISSUE THREAD

**Issue by FlyTing** [wormtql/yas#60]
无论--min-level属性填20还是+20，最终都会把所有5星圣遗物全部扫描完才会停止，大大增加了扫描时间
![image](https://user-images.githubusercontent.com/19819257/180699152-e3adcc25-675b-422e-aad8-21866616cff4.png)
![image](https://user-images.githubusercontent.com/19819257/180699213-3220ed08-e5cc-4f19-802e-0b0a482a7e6d.png)

**Comment by wormtql** [comment]
虽然评论的有点晚，但是还是说一下：最小等级是全部扫完再过滤的

**Comment by FlyTing** [comment]
> 虽然评论的有点晚，但是还是说一下：最小等级是全部扫完再过滤的

可是我印象中最终输出的结果里没有把不满足条件的syw给过滤掉
