### ISSUE TITLE
yas异常退出

### ISSUE THREAD

**Issue by Pzzzzz5142** [wormtql/yas#61]
报错截图

![image](https://user-images.githubusercontent.com/31173671/186328708-157eb37b-acd3-4397-9327-e30b2c71e2ae.png)

![image](https://user-images.githubusercontent.com/31173671/186328786-eedb9932-0968-42f8-84ed-1fb22411da13.png)

实测在0.1.9-rc1也有一样的问题。

**Comment by AcademicDog** [comment]
一样的问题

**Comment by AcademicDog** [comment]
已解决，将画面从1920x1080独占全屏改为1600x900窗口，就可以正常扫描

**Comment by Pzzzzz5142** [comment]
（我是4k

**Comment by Pzzzzz5142** [comment]
估计是4k分辨率没做适配（

**Comment by Flocculus** [comment]
一个问题，改分辨率也没用

**Comment by wormtql** [comment]
用新的0.1.9

**Comment by Pzzzzz5142** [comment]
> 用新的0.1.9

感谢，问题解决了。但目前检测新版本都是默认检测的0.1.9-rc1，感觉应该在检测更新的时候区分一下是否检测测试版。
