### ISSUE TITLE
双击exe么有反应，是缺少什么环境吗

### ISSUE THREAD

**Issue by Milk5253** [wormtql/yas#62]
鼠标变成个圈转一下，然后就没了，任务管理器也没有进程

**Comment by wormtql** [comment]
右键管理员运行

**Comment by SolSolis** [comment]
遇到了同样的问题，反馈一下。
W10 21HW，Win Defender关闭，v0.1.8管理员运行正常，v0.1.9管理员运行没有cmd对话框也没有进程。

**Comment by wormtql** [comment]
怀疑是upx压缩的问题，试试这个https://github.com/wormtql/yas/suites/7954179784/artifacts/339765354

**Comment by SolSolis** [comment]
感谢大佬及时回复~
这次能打开，不过有报错...
![RT5QY% 14~J)0C`TRRNX(OL](https://user-images.githubusercontent.com/14959249/187035419-11236f9c-1335-428f-9f07-10b8cfda0ac3.png)

**Comment by SolSolis** [comment]
重新下了发布版v0.1.9测试正常了，不知道发生了什么...感谢大佬，不折腾您了~
