### ISSUE TITLE
Support GOOD format 

### ISSUE THREAD

**Issue by seriaati** [wormtql/yas#68]
The GOOD format is the format used by Genshin Optimizer: https://frzyc.github.io/genshin-optimizer/#/characters
I wish the export option can have GOOD as well instead of mona, which I don't use.

**Comment by wormtql** [comment]
I won't maintain GOOD format, but pr is welcome

**Comment by seriaati** [comment]
I don't know how to code in Rust, but I've made one in python: https://github.com/seriaati/mona-to-good

**Comment by seriaati** [comment]
Can you make a release of this version? The current one doesn't have an option to export in GOOD.
