### ISSUE TITLE
我可以从播放视频中导入工件吗？

### ISSUE THREAD

**Issue by mimikun** [wormtql/yas#71]
自动操作鼠标的工具可能被认为是作弊工具。

原来的:
Can I import artifacts from play videos?
Tools that automatically operate the mouse may be considered cheat tools.

**Comment by sandboxdream** [comment]
Title:请求增加通过视频导入圣遗物的功能

自动操作鼠标可能会被判定为作弊



---

but infect there are thousands of players are useing software like this,I don't hear anyone had been banned because these tools.

**Comment by wormtql** [comment]
currently not supported
