### ISSUE TITLE
I don't see the option to output as GOOD format

### ISSUE THREAD

**Issue by seriaati** [wormtql/yas#78]
![image](https://user-images.githubusercontent.com/61446626/202086713-b380c27a-a4c9-447c-a8c1-1e3615d4b9ba.png)
Using the latest version of YAS

**Comment by wormtql** [comment]
Use the lastest commit on the main branch, it's not released yet.

**Comment by seriaati** [comment]
I'm struggling to build from source code

**Comment by wormtql** [comment]
Just clone the repo and run `cargo build --release`, you can view the workflow file for a detailed build process.

**Comment by seriaati** [comment]
okay, i'll try it

**Comment by seriaati** [comment]
a lot of warnings popped up and I'm stuck at 332/333 right now
```py
warning: unused `Result` that must be used
   --> src\main.rs:141:5
    |
141 |     stdin().read_line(&mut s);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

    Building [=======================> ] 332/333: yas(bin)
```

**Comment by seriaati** [comment]
https://mystb.in/LayoutFuelRio

**Comment by wormtql** [comment]
warning can be ignored, you can wait until successfully built.

**Comment by seriaati** [comment]
nevermind, found it.
