### ISSUE TITLE
Bug with the GOOD format

### ISSUE THREAD

**Issue by seriaati** [wormtql/yas#79]
There is a bug that makes the ER value very high:
```json
{
            "setKey": "BlizzardStrayer",
            "slotKey": "circlet",
            "level": 20,
            "rarity": 5,
            "mainStatKey": "critDMG_",
            "location": "",
            "lock": false,
            "substats":
            [
                {
                    "key": "def",
                    "value": 16.0
                },
                {
                    "key": "enerRech_",
                    "value": 1550.0
                },
                {
                    "key": "atk",
                    "value": 66.0
                },
                {
                    "key": "critRate_",
                    "value": 3.1
                }
            ]
        },
```
![image](https://user-images.githubusercontent.com/61446626/202408117-0b9aee32-56bb-433b-b02c-ba81c369c23c.png)

**Comment by seriaati** [comment]
![image](https://user-images.githubusercontent.com/61446626/204167592-d4d08a16-866b-47b0-b850-622f4de542cc.png)

**Comment by wormtql** [comment]
run `yas --verbose` and see the raw recognition results

**Comment by seriaati** [comment]
YasScanResult { name: "破冰踏雪的回音", main_stat_name: "暴击伤害", main_stat_value: "62.2%", sub_stat_1: "防御力+16", sub_stat_2: "元素充能效率+15.5", sub_stat_3: "攻击力+66", sub_stat_4: "暴击率+3.1%", level: "+20", equip: "神里绫已装备", star: 5 }

**Comment by wormtql** [comment]
I'll fix this in the next release, and if you like, you can run `yas --dump` to see the image captured and it's a hint of why the recognition fails.
