### ISSUE TITLE
有考虑改用onnxruntime提高推理的性能吗？

### ISSUE THREAD

**Issue by yuanyan3060** [wormtql/yas#80]

**Comment by wormtql** [comment]
有证据表明onnxruntime更快吗，此外yas的性能瓶颈在于圣遗物切换而不是推理

**Comment by yuanyan3060** [comment]
> 有证据表明onnxruntime更快吗，此外yas的性能瓶颈在于圣遗物切换而不是推理

我这边跑飞桨ocr，tract显著慢于onnxruntime，不过你们用的ocr和飞桨算子不一样，我不确定在你们的模型上也是这样
既然ocr不是瓶颈，那看来没有必要引入onnxruntime了
