### ISSUE TITLE
最新版扫描出来全是error

### ISSUE THREAD

**Issue by forchannot** [wormtql/yas#81]
![image](https://user-images.githubusercontent.com/100580891/206116289-f22621be-3f93-493d-a491-1776f66b5b90.png)

**Comment by forchannot** [comment]
补充一下，这是命令行模式指定了最小圣遗物等级为20和最小星级为5发生了这种，直接运行程序没报错

**Comment by wormtql** [comment]
用最新的release，之前那个的确有问题

**Comment by Daniel-1101** [comment]
> 用最新的release，之前那个的确有问题

我刚下了最新的，扫不出来呀，都是error.

**Comment by wormtql** [comment]
首先确保你是最新的（可以重新下载试试），其次最好录屏，或者截图（包括黑框输出以及游戏内截图）

**Comment by UtsuhoReiuji** [comment]
遇到了同样的问题，识别时大量的error日志，识别的名字有误，识别两屏以后就停止了。
使用的版本是最新的0.1.11, 出现问题之后我往回逐个尝试了旧版本一直到0.1.9， 都有问题，推测是3.3新版本游戏端更新了什么东西导致识别有误

![image](https://user-images.githubusercontent.com/24854073/206726825-e56364de-fdb7-46f7-b4bd-e2ea4df2adfe.png)
![image](https://user-images.githubusercontent.com/24854073/206726941-60290e44-33d8-4696-b254-48478d538425.png)

**Comment by lxsWestar** [comment]
> 遇到了同样的问题，识别时大量的错误日志，识别的名字有错，识别两屏以后就停止了（停止在图2中的千岩羽毛）。使用的版本的出霙1,最新 1.1.1后来我去回避个试了老版本一直到0.1.9，都有问题，推测是3.3新版本游戏端更新了什么东西导致识别有误
> 
> * 补足，没有使用任何外部参数启动，直接右键管理员运行
> 
> ![图片](https://user-images.githubusercontent.com/24854073/206726825-e56364de-fdb7-46f7-b4bd-e2ea4df2adfe.png) ![图片](https://user-images.githubusercontent.com/24854073/206726941-60290e44-33d8-4696-b254-48478d538425.png)

右边显示圣遗物的界面位置有点变化，往下拖一节，让它自动回弹成为这个样子就能解决
![image](https://user-images.githubusercontent.com/45232632/207302168-c4e33fbf-d1d1-48e6-9462-e0ea4b30840e.png)
