### ISSUE TITLE
无法进行全部扫描，且扫描日志中报错

### ISSUE THREAD

**Issue by ziyu404** [wormtql/yas#82]
![image](https://user-images.githubusercontent.com/111732141/206860598-286b4bec-68c1-4f07-893c-906fac09bb01.png)
![image](https://user-images.githubusercontent.com/111732141/206860611-7393b044-1f94-45d2-aea8-0d8f19810fd4.png)

**Comment by ziyu404** [comment]
使用版本为当前最新版

**Comment by wormtql** [comment]
确保圣遗物详情是拉到最上面的。一定要让圣遗物的名字露出来

**Comment by lxsWestar** [comment]
![image](https://user-images.githubusercontent.com/45232632/207301413-ba077d7a-a72f-412e-b05f-f346b1406f53.png)
![image](https://user-images.githubusercontent.com/45232632/207301494-89ab9724-6604-4f49-b914-18f96d6fe60d.png)
把右边那个显示圣遗物的界面往下拖一下然后让它回弹
![image](https://user-images.githubusercontent.com/45232632/207301739-e7d641e1-a5d7-4489-8021-afb31112e5ed.png)
使得右边界面最上面和左边对齐
