### ISSUE TITLE
跨平台支持

### ISSUE THREAD

**Issue by poly000** [wormtql/yas#90]
## 屏幕捕获
[screenshots-rs](https://github.com/nashaofu/screenshots-rs)
支持linux(x11/wayland) Mac OS 和 Windows

### Andorid

[无root方式 from Android 5.0](https://developer.android.com/reference/android/media/projection/MediaProjection)

### linux(x11+wayland)/mac/windows
[enigo](https://github.com/enigo-rs/enigo) 自带x11支持
wayland可以暂时不考虑，因为wine也运行在Xwayland..

### Android
无障碍服务

### linux (wine)
禁用虚拟桌面后以wine启动原神，原神窗口标题为“原神”

### Android
直接由yas切换到原神的Activaty？

**Comment by wormtql** [comment]
感觉可以尝试跨平台
