### ISSUE TITLE
Use stdin/stdout on Windows when possible instead of creating a new Console window

### ISSUE THREAD

**Issue by poscat0x04** [wormtql/yas#99]
Currently, `yas` opens a new `cmd.exe`-like console window/buffer even if being executed inside a terminal like Window Terminal. This causes a few issues:

1. Executing `yas.exe --help` only prints the help message onto the newly created window, which then immediately closes after `yas.exe` exits, leaving the user with no help messages whatsoever.
2. Essentially the same issue as 1. when your supply `yas` with incorrect CLI arguments: no message is delivered.
3. The console window does not support copying.

Proposed solution:

Print to stdout by default. Only open a console when you're sure that the program is not already in a terminal.

**Comment by Fachep** [comment]
没复现
![image](https://user-images.githubusercontent.com/31302548/211143437-aa3056e6-b9cb-44b6-a32c-e6fddb7b3c27.png)
![image](https://user-images.githubusercontent.com/31302548/211143477-c0e24c0b-1c8a-48ca-8a77-8c31e3833e9c.png)

**Comment by poscat0x04** [comment]
Running `yas` inside a shell that's being run at administrator's privilege does solve this issue. Though I think `yas` should work inside an unprivileged shell as well.

**Comment by poscat0x04** [comment]
This and https://github.com/wormtql/yas/issues/100 are possibly two sides of the same coin.
